from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_CipherWindow(object):
    def setupUi(self, CipherWindow):
        CipherWindow.setObjectName("CipherWindow")
        CipherWindow.resize(800, 560)
        CipherWindow.setMinimumSize(QtCore.QSize(800, 560))
        CipherWindow.setMaximumSize(QtCore.QSize(800, 560))
        CipherWindow.setWindowIcon(QtGui.QIcon('cipher.ico'))
        self.cipher_centralwidget = QtWidgets.QWidget(CipherWindow)
        self.cipher_centralwidget.setObjectName("centralwidget")
        self.cipher_horizontal_layout_widget = QtWidgets.QWidget(self.cipher_centralwidget)
        self.cipher_horizontal_layout_widget.setGeometry(QtCore.QRect(0, 30, 801, 421))
        self.cipher_horizontal_layout_widget.setObjectName("horizontalLayoutWidget")
        self.cipher_horizontal_layout = QtWidgets.QHBoxLayout(self.cipher_horizontal_layout_widget)
        self.cipher_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.cipher_horizontal_layout.setObjectName("horizontalLayout")
        self.text_input = QtWidgets.QTextEdit(self.cipher_horizontal_layout_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_input.setFont(font)
        self.text_input.setObjectName("text_input")
        self.text_input.setPlaceholderText("Введите текст")
        self.cipher_horizontal_layout.addWidget(self.text_input)
        self.text_output = QtWidgets.QTextEdit(self.cipher_horizontal_layout_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_output.setFont(font)
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.text_output.setPlaceholderText("Зашифрованный текст")
        self.cipher_horizontal_layout.addWidget(self.text_output)
        self.ciph = QtWidgets.QComboBox(self.cipher_centralwidget)
        self.ciph.setGeometry(QtCore.QRect(0, 460, 801, 31))
        self.ciph.setObjectName("ciph")
        self.ciph.addItem("")
        self.ciph.addItem("")
        self.btn_add_cipher = QtWidgets.QPushButton(self.cipher_centralwidget)
        self.btn_add_cipher.setGeometry(QtCore.QRect(0, 500, 401, 31))
        self.btn_add_cipher.setObjectName("add_cipher")
        self.btn_ciph_text = QtWidgets.QPushButton(self.cipher_centralwidget)
        self.btn_ciph_text.setGeometry(QtCore.QRect(400, 500, 401, 31))
        self.btn_ciph_text.setObjectName("btn_ciph_text")
        self.btn_login = QtWidgets.QPushButton(self.cipher_centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(700, 0, 93, 28))
        self.btn_login.setObjectName("btn_login")
        self.btn_logout = QtWidgets.QPushButton(self.cipher_centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(700, 0, 90, 28))
        self.btn_logout.setObjectName("btn_logout")
        self.btn_logout.hide()
        self.name_user = QtWidgets.QLabel(self.cipher_centralwidget)
        self.name_user.setGeometry(QtCore.QRect(538, -2, 161, 31))
        self.name_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_user.setIndent(-1)
        self.name_user.setObjectName("name_user")
        CipherWindow.setCentralWidget(self.cipher_centralwidget)

        self.retranslateUi(CipherWindow)
        QtCore.QMetaObject.connectSlotsByName(CipherWindow)

    def retranslateUi(self, CipherWindow):
        _translate = QtCore.QCoreApplication.translate
        CipherWindow.setWindowTitle(_translate("CipherWindow", "Шифратор"))
        self.ciph.setItemText(0, _translate("CipherWindow", "Шифр Морзе"))
        self.ciph.setItemText(1, _translate("CipherWindow", "Шифр Цезаря"))
        self.btn_add_cipher.setText(_translate("CipherWindow", "Добавить свой шифр"))
        self.btn_ciph_text.setText(_translate("CipherWindow", "Шифровать"))
        self.btn_login.setText(_translate("CipherWindow", "Войти"))
        self.btn_logout.setText(_translate("CipherWindow", "Выйти"))
        self.name_user.setText(_translate("CipherWindow", "Guest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CipherWindow = QtWidgets.QMainWindow()
    ui = Ui_CipherWindow()
    ui.setupUi(CipherWindow)
    CipherWindow.show()
    sys.exit(app.exec_())
